# Generated by Django 4.0.1 on 2022-02-08 08:39

from django.db import migrations, models

def seeder(apps, schema_editor):
    seed_data = [
        {"name": "칠 수 없다 으라챠챠!!", "age": 3},
        {"name": "mango", "age": 3},
        {"name": "ruru", "age": 5},
        {"name": "kitty", "age": 1},
    ]
    Users = apps.get_model('chilsutest', 'Users')
    for cat in seed_data:
        Users.objects.create(name=cat["name"], age=cat["age"])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.RunPython(seeder)
    ]
